spring:
  application:
    name: fintrack-backend

  datasource:
    url: jdbc:mysql://localhost:3306/fintrack
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: 4f6e54727573744d65466f7246696e547261636b323032364a57545365637265744b657931323334353637383930
  expiration: 86400000